# Generated by Django 5.2.3 on 2025-06-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=20, unique=True)),
                ('math', models.FloatField(blank=True, null=True)),
                ('literature', models.FloatField(blank=True, null=True)),
                ('foreign_language', models.FloatField(blank=True, null=True)),
                ('physics', models.FloatField(blank=True, null=True)),
                ('chemistry', models.FloatField(blank=True, null=True)),
                ('biology', models.FloatField(blank=True, null=True)),
                ('history', models.FloatField(blank=True, null=True)),
                ('geography', models.FloatField(blank=True, null=True)),
                ('civic_education', models.FloatField(blank=True, null=True)),
                ('foreign_language_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
